apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: gateway-port
