apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      name: gateway-deployment
      labels:
        app: gateway-deployment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway-deployment
          image: "ghcr.io/unspokenteam/gateway"
          imagePullPolicy: IfNotPresent
          env:
            - name: "INVITE_SERVICE_HOST"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INVITE_SERVICE_HOST
            - name: "INVITE_SERVICE_PORT"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INVITE_SERVICE_PORT
            - name: "EVENT_SERVICE_HOST"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: EVENT_SERVICE_HOST
            - name: "EVENT_SERVICE_PORT"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: EVENT_SERVICE_PORT
            - name: "IDENTITY_SERVICE_HOST"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: IDENTITY_SERVICE_HOST
            - name: "IDENTITY_SERVICE_PORT"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: IDENTITY_SERVICE_PORT
            - name: "NOTIFICATION_SERVICE_HOST"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: NOTIFICATION_SERVICE_HOST
            - name: "NOTIFICATION_SERVICE_PORT"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: NOTIFICATION_SERVICE_PORT
            - name: "REDIS_URL"
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: REDIS_URL
          ports:
            - containerPort: 8084
              name: gateway-port
      restartPolicy: Always
      