apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-deployment
  template:
    metadata:
      name: notification-service-deployment
      labels:
        app: notification-service-deployment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service-deployment
          image: "ghcr.io/unspokenteam/notification_service"
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: nos-port
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: DATABASE_URL
            - name: "ENVIRONMENT"
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: ENVIRONMENT
      restartPolicy: Always
      