apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
spec:
  selector:
    app: notification-service-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: nos-port
  clusterIP: None
  type: ClusterIP
