apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      name: postgres-deployment
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres-deployment
          image: 'ghcr.io/unspokenteam/custom_postgres:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres-port
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: identity-service-storage
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: identity-service-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      restartPolicy: Always
