apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    db: postgres
spec:
  selector:
    app: postgres-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-port
      nodePort: 31000

  type: NodePort
