[tool.mypy]
strict = true
ignore_missing_imports = true
explicit_package_bases = true
exclude = "gateway"
# Disabled errors
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = ["google.*", "fastapi", "generated"]
ignore_errors = true
ignore_missing_imports = true
disallow_untyped_decorators = false


[tool.ruff]
exclude = [
    ".venv",
    "__pycache__",
    "event_service/src/generated",
    "notification_service/src/generated",
    "invite_service/generated",
    "invite_service/src/generated",
    "identity_service/generated",
    "gateway/generated",
    "singleton.py",
    "event_service/src/constants/constants.py",
    "notification_service/src/constants/constants.py"
]

line-length = 119
indent-width = 4

target-version = "py311"

[tool.ruff.lint]
select = ["D", "E4", "E7", "E9", "F", "I", "ANN", "S", "RET", "FIX", "RUF", "TD", "ARG"]
ignore = [
    "E226",
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "D203", "D212", "D214", "D215",
    "D301",
    "D400", "D401", "D402", "D404", "D405", "D406", "D407", "D408", "D409", "D410", "D411",
    "D412" , "D413", "D414", "D416", "D417",
    "E266",
    "ANN101", "ANN102", "ANN401"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "prisma", "proto", "local", "local-folder"]
default-section = "local-folder"
from-first = true
known-third-party = ["grpc"]


[tool.ruff.lint.isort.sections]
"prisma" = ["prisma"]
"proto" = ["proto"]
"local" = ["src", "db", "utils", "errors"]
