apiVersion: apps/v1
kind: Deployment
metadata:
  name: invite-service-deployment
  labels:
    app: invite-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invite-service-deployment
  template:
    metadata:
      name: invite-service-deployment
      labels:
        app: invite-service-deployment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: invite-service-deployment
          image: "ghcr.io/unspokenteam/invite_service"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: ins-port
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: invite-service-secret
                  key: DATABASE_URL
      restartPolicy: Always
