apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    db: redis-deployment
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis-port
      protocol: TCP
  selector:
    db: redis-deployment
