apiVersion: v1
kind: Service
metadata:
  name: event-service-service
spec:
  selector:
    app: event-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: evs-port
  clusterIP: None
