apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
  labels:
    app: identity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-deployment
  template:
    metadata:
      name: identity-service-deployment
      labels:
        app: identity-service-deployment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: identity-service-deployment
          image: 'ghcr.io/unspokenteam/identity_service:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: ids-port
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: DATABASE_URL
            - name: "ACCESS_SECRET"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: ACCESS_SECRET
            - name: "REFRESH_SECRET"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: REFRESH_SECRET
            - name: "ENVIRONMENT"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: ENVIRONMENT
            - name: "ACCESS_TOKEN_EXPIRATION"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: ACCESS_TOKEN_EXPIRATION
            - name: "REFRESH_TOKEN_EXPIRATION"
              valueFrom:
                secretKeyRef:
                  name: identity-service-secret
                  key: REFRESH_TOKEN_EXPIRATION
      restartPolicy: Always
